#Evan Heaton
#:wq

program: main.o readData.o secondGreatest.o
	g++ -o Lab9 main.o readData.o secondGreatest.o
main.o: main.cpp
	g++ -c main.cpp
readData.o: readData.cpp
	g++ -c readData.cpp
secondGreatest.o: secondGreatest.cpp
	g++ -c secondGreatest.cpp
clean:
	rm *.o
