#!/bin/bash
clear
hname=`hostname`
echo 'Welcome on $hname!'
echo 'Opps.'
echo
echo "Welcome on $hname!"
echo -n "It is currently: ";date
echo -n "I am currently logged on as: ";whoami
echo -n "I am currently in the directory: ";pwd
echo "`bash --version`"
